"""The Joinery answer file — `.workshop/answers.toml`.

This tracked file records what Joinery installed in a project: version, tier,
language, the set of files Joinery wrote, the set of files Joinery preserved
during adoption, and the hooks installed. It is the authoritative index of
the framework's footprint and the precondition for future `workshop diff`,
`workshop update`, and `workshop migrate` flows.

Schema is fixed and small enough that a hand-written serializer beats pulling
in a TOML writer dependency. Reading uses stdlib tomllib (Python 3.11+).
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from joinery import __version__

ANSWER_FILE_RELPATH = Path(".workshop") / "answers.toml"

Mode = Literal["init", "adopt"]


@dataclass
class Manifest:
    """In-memory representation of `.workshop/answers.toml`."""

    project_name: str
    tier: str
    language: str
    mode: Mode
    joinery_version: str = __version__
    created_at: str = ""  # ISO 8601 UTC; filled by write_manifest() if empty
    managed_files: list[str] = field(default_factory=list)
    preserved_files: list[str] = field(default_factory=list)
    hooks_installed: list[str] = field(default_factory=list)
    hooks_preserved: list[str] = field(default_factory=list)


def write_manifest(target: Path, manifest: Manifest) -> Path:
    """Serialize manifest to `<target>/.workshop/answers.toml`."""
    if not manifest.created_at:
        manifest.created_at = datetime.now(tz=UTC).isoformat(timespec="seconds")
    path = target / ANSWER_FILE_RELPATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_serialize(manifest), encoding="utf-8")
    return path


def read_manifest(target: Path) -> Manifest | None:
    """Read `.workshop/answers.toml`. Returns None if not present."""
    path = target / ANSWER_FILE_RELPATH
    if not path.is_file():
        return None
    with path.open("rb") as f:
        data = tomllib.load(f)
    mode = data["mode"]
    if mode not in ("init", "adopt"):
        raise ValueError(f"Invalid mode in {path}: {mode!r}")
    files = data.get("files", {})
    hooks = data.get("hooks", {})
    return Manifest(
        project_name=str(data["project_name"]),
        tier=str(data["tier"]),
        language=str(data["language"]),
        mode=mode,
        joinery_version=str(data["joinery_version"]),
        created_at=str(data["created_at"]),
        managed_files=[str(p) for p in files.get("managed", [])],
        preserved_files=[str(p) for p in files.get("preserved", [])],
        hooks_installed=[str(p) for p in hooks.get("installed", [])],
        hooks_preserved=[str(p) for p in hooks.get("preserved", [])],
    )


def _serialize(manifest: Manifest) -> str:
    """Hand-written TOML serializer for the fixed answer-file schema."""
    lines = [
        "# Generated by Joinery — do not edit by hand.",
        "# Records what Joinery installed/manages in this project.",
        "# Used by `workshop diff`, `workshop update`, and `workshop migrate`.",
        "",
        f'joinery_version = "{manifest.joinery_version}"',
        f'mode = "{manifest.mode}"',
        f'tier = "{manifest.tier}"',
        f'language = "{manifest.language}"',
        f'project_name = "{_escape(manifest.project_name)}"',
        f'created_at = "{manifest.created_at}"',
        "",
        "[files]",
        f"managed = {_string_list(manifest.managed_files)}",
        f"preserved = {_string_list(manifest.preserved_files)}",
        "",
        "[hooks]",
        f"installed = {_string_list(manifest.hooks_installed)}",
        f"preserved = {_string_list(manifest.hooks_preserved)}",
        "",
    ]
    return "\n".join(lines)


def _escape(s: str) -> str:
    """Escape a string for TOML basic-string context."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _string_list(items: list[str]) -> str:
    """Serialize a list of strings as a TOML array, sorted, on multiple lines if non-empty."""
    if not items:
        return "[]"
    sorted_items = sorted(items)
    formatted = ",\n    ".join(f'"{_escape(item)}"' for item in sorted_items)
    return f"[\n    {formatted},\n]"
